[package]
name = "json"
version = "1.4.0"
description = "JSON parser and stringifier for Motoko"
repository = "https://github.com/Demali-876/json"
keywords = [ "json", "parse", "stringfy", "validate" ]
license = "MIT"

[dependencies]
xtended-numbers = "0.3.1"

[dev-dependencies]
test = "2.0.0"
